# Generated by Django 3.0.6 on 2020-06-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodict',
            new_name='Product',
        ),
    ]
