# Generated by Django 3.0.6 on 2020-06-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200629_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='products/%Y/%m/%d/'),
        ),
    ]
