# Generated by Django 3.0.6 on 2020-07-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200629_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='section_id',
            new_name='section',
        ),
    ]
