# Generated by Django 3.0.8 on 2020-08-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default='2020-08-09', verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
