# Generated by Django 3.0.8 on 2020-08-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200809_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='product',
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(through='app.ArticleRelation', to='app.Product'),
        ),

    ]
