# Generated by Django 3.0.8 on 2020-08-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200809_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlerelation',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Товар в статье', 'verbose_name_plural': 'Товары в статье'},
        ),
        migrations.AlterField(
            model_name='article',
            name='caption',
            field=models.CharField(max_length=150, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='articlerelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product', verbose_name='ТОвар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inf',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='products/%Y/%m/%d/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Товарная секция'),
        ),
    ]
