# Generated by Django 3.0.8 on 2020-08-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200809_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2020-08-09', verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlerelation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlerelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product', verbose_name='Товар'),
        ),
    ]
