# Generated by Django 3.0.8 on 2020-08-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200809_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='articlerelation',
            options={'verbose_name': 'Товар в статье', 'verbose_name_plural': 'Товары в статье'},
        ),
        migrations.RemoveField(
            model_name='articlerelation',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2020-08-09', verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
