# Generated by Django 3.0.8 on 2020-08-09 14:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_auto_20200809_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Статья о товаре', 'verbose_name_plural': 'Статьи о товаре'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв о товаре', 'verbose_name_plural': 'Отзывы о товаре'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Товарная секция', 'verbose_name_plural': 'Товарные секции'},
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.PositiveIntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 19, 58, 36, 636221), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
