# Generated by Django 3.0.8 on 2020-08-10 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200809_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='session',
        ),
        migrations.AddField(
            model_name='review',
            name='sessionid',
            field=models.CharField(default='2020-08-10', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 11, 59, 27, 835814), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
