# Generated by Django 3.0.8 on 2020-08-12 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200810_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['number'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 10, 51, 3, 606028), verbose_name='Дата'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Product', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
