# Generated by Django 3.0.8 on 2020-08-12 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200812_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 15, 46, 19, 769048), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 15, 46, 19, 771048), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Пользователь'),
        ),
    ]
