# Generated by Django 3.0.8 on 2020-08-13 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200812_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sessionid',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 16, 28, 48, 968900), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 16, 28, 48, 969900), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='orderrelation',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
